gpu: true
data_dir: ""
save: false
save_freq: 10000
load: false
load_dir: "./logdir/[env]/PSDRL-[name]/[seed]/checkpoints/[timestep]/"
visual: False


algorithm:
  name: PSDRL
  reward_prior: 1e-1
  transition_prior: 1e-3
  update_freq: 1e3
  warmup_length: 1e5
  warmup_freq: 1e2
  policy_noise: 0.0
  n_samples: 1
  temp: 1e-4

experiment:
  suite: bsuite
  env: 5
  unscaled_move_cost: 0.01
  test: true
  steps: 5e4
  time_limit: 1500
  test_freq: 2e3
  name: "PSDRL"
  seed: None

replay:
  capacity: 1e5
  batch_size: 100
  sequence_length: 50

transition:
  training_iterations: 30
  hidden_dim: 150
  gru_dim: 1
  learning_rate: 1e-3
  window_length: 4

value:
  training_iterations: 30
  hidden_dim: 150
  learning_rate: 1e-4
  target_update_freq: 4
  discount: 0.99

terminal:
  training_iterations: 30
  hidden_dim: 150
  learning_rate: 1e-3

representation:
  training_iterations: 100
  learning_rate: 1e-3
  embed_dim: 1000
