gpu: true
data_dir: ""
save: false
save_freq: 10000
load: false
load_dir: "./logdir/[env]/PSDRL-[name]/[seed]/checkpoints/[timestep]/"
visual: False


algorithm:
  name: Ensemble
  update_freq: 1e1
  warmup_length: 1e1
  warmup_freq: 1e1
  ensemble_size: 10
  policy_noise: 0.0

experiment:
  suite: bsuite
  env: 5
  test: true
  steps: 1e6
  time_limit: 27000
  test_freq: 1e4
  name: "Ensemble"
  seed: None

replay:
  capacity: 1e5
  batch_size: 100
  sequence_length: 10

transition:
  training_iterations: 100
  hidden_dim: 1500
  gru_dim: 1
  learning_rate: 1e-3
  window_length: 4

value:
  training_iterations: 100
  hidden_dim: 1500
  learning_rate: 1e-4
  target_update_freq: 4
  discount: 0.99

terminal:
  training_iterations: 100
  hidden_dim: 1500
  learning_rate: 1e-3

representation:
  training_iterations: 100
  learning_rate: 1e-3
  embed_dim: 1000
